# Generated by Django 4.2 on 2023-04-28 12:51

from django.db import migrations, models
import taskboard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0007_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(default='new', validators=[taskboard.validators.task_state_validator], verbose_name=20),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(validators=[taskboard.validators.task_action_validator], verbose_name=20),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='state',
            field=models.CharField(default='new', validators=[taskboard.validators.task_state_validator], verbose_name=20),
        ),
    ]
