# Generated by Django 4.2 on 2023-05-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0008_alter_task_state_alter_taskhistory_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='task',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
